server:
  port: 8769
spring:
  application:
    name: zuul
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: client
    api-b:
      path: /api-b/**
      serviceId: feign